services:
  - type: web
    name: smart-city-dashboard
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
