services:
  - type: web
    name: smart-city-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
