services:
  - type: web
    name: smart-city-dashboard
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm ci && npm run build && cd ..
    staticPublishPath: ./frontend/build
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048
    healthCheckPath: /
    autoDeploy: true
