services:
  - type: web
    name: smart-city-dashboard
    env: python
    buildCommand: |
      export NODE_OPTIONS="--max-old-space-size=2048"
      pip install -r requirements.txt
      cd frontend && npm install && NODE_ENV=production npm run build && cd ..
    staticPublishPath: ./frontend/build
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --threads 4 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
